export const TODAY_ARRIVALS = [
  {
    id: 74,
    guestNameAr: 'احمد علي محمد',
    guestNameEn: 'Ahmed Ali Mohamed',
    phone: '0912345678',
    roomCount: 1,
    startDateAr: '10-05-2026',
    endDateAr: '25-05-2026',
    startDateEn: '10 May 2026',
    endDateEn: '25 May 2026',
    priceAr: '4250,00 د.ل.',
    priceEn: '4,250.00 LYD',
  },
  {
    id: 72,
    guestNameAr: 'فاطمة حسن إبراهيم',
    guestNameEn: 'Fatima Hassan Ibrahim',
    phone: '0928765432',
    roomCount: 2,
    startDateAr: '17-05-2026',
    endDateAr: '22-05-2026',
    startDateEn: '17 May 2026',
    endDateEn: '22 May 2026',
    priceAr: '1800,00 د.ل.',
    priceEn: '1,800.00 LYD',
  },
]

export const CHECK_IN_DETAILS = {
  74: {
    id: 74,
    guestNameAr: 'احمد علي محمد',
    guestNameEn: 'Ahmed Ali Mohamed',
    phone: '+01111111111',
    idNumber: '21111111',
    bookingDate: '2026-04-10',
    arrivalDate: '2026-04-10',
    departureDate: '2026-04-15',
    totalAmountAr: '4250,00 د.ل.',
    totalAmountEn: '4,250.00 LYD',
    paidAmountAr: '1,000 د.ل.',
    paidAmountEn: '1,000 LYD',
    remainingAmountAr: '3,250 د.ل.',
    remainingAmountEn: '3,250 LYD',
    nationalityAr: 'مصري',
    nationalityEn: 'Egyptian',
    professionAr: 'Event Planner',
    professionEn: 'Event Planner',
    birthDate: '1992-03-12',
    visitPurposeAr: 'Family Reunion',
    visitPurposeEn: 'Family Reunion',
    genderAr: 'ذكر',
    genderEn: 'Male',
    source: 'Booking.com',
    notesAr: 'سيصل مع العائلة. يحتاج إلى غرف في نفس الطابق إذا أمكن',
    notesEn: 'Will arrive with family. Needs rooms on the same floor if possible',
    totalRooms: 3,
    adults: 5,
    children: 1,
    rooms: [
      {
        id: 1,
        typeAr: 'Suite',
        typeEn: 'Suite',
        adults: 1,
        children: 2,
        fromDate: '2026-04-10',
        toDate: '2026-04-12',
        nightsAr: '2 ليالي',
        nightsEn: '2 nights',
        priceAr: '450 د.ل.',
        priceEn: '450 LYD',
      },
      {
        id: 2,
        typeAr: 'Double',
        typeEn: 'Double',
        adults: 0,
        children: 2,
        fromDate: '2026-04-10',
        toDate: '2026-04-12',
        nightsAr: '2 ليالي',
        nightsEn: '2 nights',
        priceAr: '250 د.ل.',
        priceEn: '250 LYD',
      },
      {
        id: 3,
        typeAr: 'Single',
        typeEn: 'Single',
        adults: 0,
        children: 1,
        fromDate: '2026-04-10',
        toDate: '2026-04-12',
        nightsAr: '2 ليالي',
        nightsEn: '2 nights',
        priceAr: '150 د.ل.',
        priceEn: '150 LYD',
      },
    ],
    totalNightsAr: '6 ليالي',
    totalNightsEn: '6 nights',
    totalRoomsPriceAr: '1,700 د.ل.',
    totalRoomsPriceEn: '1,700 LYD',
  },
  72: {
    id: 72,
    guestNameAr: 'فاطمة حسن إبراهيم',
    guestNameEn: 'Fatima Hassan Ibrahim',
    phone: '+0928765432',
    idNumber: '19876543',
    bookingDate: '2026-05-17',
    arrivalDate: '2026-05-17',
    departureDate: '2026-05-22',
    totalAmountAr: '1800,00 د.ل.',
    totalAmountEn: '1,800.00 LYD',
    paidAmountAr: '900 د.ل.',
    paidAmountEn: '900 LYD',
    remainingAmountAr: '900 د.ل.',
    remainingAmountEn: '900 LYD',
    nationalityAr: 'ليبي',
    nationalityEn: 'Libyan',
    professionAr: 'طبيبة',
    professionEn: 'Doctor',
    birthDate: '1988-07-22',
    visitPurposeAr: 'عمل',
    visitPurposeEn: 'Business',
    genderAr: 'أنثى',
    genderEn: 'Female',
    source: 'مباشر',
    sourceEn: 'Direct',
    notesAr: 'تفضيل غرفة هادئة',
    notesEn: 'Prefers a quiet room',
    totalRooms: 2,
    adults: 2,
    children: 0,
    rooms: [
      {
        id: 1,
        typeAr: 'Double',
        typeEn: 'Double',
        adults: 2,
        children: 0,
        fromDate: '2026-05-17',
        toDate: '2026-05-22',
        nightsAr: '5 ليالي',
        nightsEn: '5 nights',
        priceAr: '1200 د.ل.',
        priceEn: '1,200 LYD',
      },
      {
        id: 2,
        typeAr: 'Single',
        typeEn: 'Single',
        adults: 0,
        children: 0,
        fromDate: '2026-05-17',
        toDate: '2026-05-22',
        nightsAr: '5 ليالي',
        nightsEn: '5 nights',
        priceAr: '600 د.ل.',
        priceEn: '600 LYD',
      },
    ],
    totalNightsAr: '10 ليالي',
    totalNightsEn: '10 nights',
    totalRoomsPriceAr: '1,800 د.ل.',
    totalRoomsPriceEn: '1,800 LYD',
  },
}
